# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-17 23:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userdash', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='addressee',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='messages_to', to='userdash.User'),
            preserve_default=False,
        ),
    ]
